### ISSUE TITLE
How to run vaping without --debug

### ISSUE THREAD

**Issue by jiberan** [20c/vaping#65] opened 2019-10-31 12:21 UTC
Hi, 
I'm running vaping on Raspbian. I have managed to run it using 
`vaping start --home=/home/vaping --debug
`

How can I run it without --debug?  
`vaping start --home=/home/vaping
`
This is not wokring. 
Can you help?
Thanks.

**Comment by grizz** [comment] 2019-10-31 12:23
Without debug it forks into the background, but still is running. Are you sure it's not working?

**Comment by jiberan** [comment] 2019-10-31 12:31
I can see, that right after I run `vaping start --home=/home/vaping
`
vaping.pid file is created. After few seconds, this file is deleted.  Also in `top` I can see that vaping is runing just for a few seconds.

**Comment by baristan93** [comment] 2019-10-31 12:48
Can confirm that. Only running vaping in debug mode works.

**Comment by vegu** [comment] 2019-10-31 12:55
@jiberan @baristan93 What python version are you guys running?

I can see a similar issue running py3.6 - py2.7 works as expected.

**Comment by baristan93** [comment] 2019-10-31 13:00
`Python 2.7.16`

**Comment by vegu** [comment] 2019-10-31 13:01
What's your output of running `pip freeze` ?

**Comment by jiberan** [comment] 2019-10-31 13:05
same here. 2.7.16.

`pip freeze`

> arandr==0.1.9
asn1crypto==0.24.0
automationhat==0.2.0
blinker==1.4
blinkt==0.1.2
buttonshim==0.0.2
Cap1xxx==0.1.3
certifi==2018.8.24
chardet==3.0.4
click==6.7
colorama==0.3.7
colorzero==1.1
configparser==3.5.0b2
cookies==2.2.1
cryptography==2.6.1
docutils==0.15.2
drumhat==0.1.0
entrypoints==0.3
enum34==1.1.6
envirophat==1.0.0
ExplorerHAT==0.4.2
Flask==1.0.2
fourletterphat==0.1.0
funcsigs==1.0.2
future==0.18.1
gevent==1.4.0
gpiozero==1.5.1
graphsrv==1.6.0
greenlet==0.4.15
gyp==0.1
idna==2.6
ipaddress==1.0.17
itsdangerous==0.24
Jinja2==2.10
keyring==17.1.1
keyrings.alt==3.1.1
lockfile==0.12.2
MarkupSafe==1.1.0
mcpi==0.1.1
microdotphat==0.2.1
mock==2.0.0
mote==0.0.4
motephat==0.0.2
munge==0.6.0
numpy==1.16.2
oauthlib==2.1.0
olefile==0.46
pantilthat==0.0.7
pbr==4.2.0
phatbeat==0.1.1
pianohat==0.1.0
picamera==1.13
picraft==1.0
pid==2.2.5
piglow==1.2.4
pigpio==1.44
Pillow==5.4.1
pluginmgr==0.5.1
pycairo==1.16.2
pycrypto==2.6.1
pyflakes==2.0.0
pygame==1.9.4.post1
PyGObject==3.30.4
pyinotify==0.9.6
PyJWT==1.7.0
pyOpenSSL==19.0.0
pyserial==3.4
python-daemon==2.2.4
pyxdg==0.25
PyYAML==5.1.2
rainbowhat==0.1.0
requests==2.21.0
requests-oauthlib==1.0.0
responses==0.9.0
RPi.GPIO==0.7.0
RTIMULib==7.2.1
scrollphat==0.0.7
scrollphathd==1.2.1
SecretStorage==2.3.1
sense-emu==1.1
sense-hat==2.2.0
simplejson==3.16.0
six==1.12.0
skywriter==0.0.7
sn3218==1.2.7
spidev==3.3
subprocess32==3.5.4
touchphat==0.0.1
twentyc.tmpl==0.2.0
twython==3.7.0
unicornhathd==0.0.4
urllib3==1.24.1
vaping==1.1.0
vodka==2.2.6
Werkzeug==0.14.1
whichcraft==0.6.1

**Comment by vegu** [comment] 2019-10-31 13:15
we'll have a look at this issue, thanks for the feedback.

will update once i know more / have a fix

**Comment by baristan93** [comment] 2019-10-31 13:38
`pip freeze`
> asn1crypto==0.24.0
certifi==2019.9.11
chardet==3.0.4
click==6.7
configparser==3.5.0b2
cryptography==2.6.1
docutils==0.15.2
entrypoints==0.3
enum34==1.1.6
Flask==1.1.1
future==0.18.2
gevent==1.4.0
graphsrv==1.6.0
greenlet==0.4.15
idna==2.8
ipaddress==1.0.17
itsdangerous==1.1.0
Jinja2==2.10.3
keyring==17.1.1
keyrings.alt==3.1.1
lockfile==0.12.2
MarkupSafe==1.1.1
munge==0.6.0
pid==2.2.5
pluginmgr==0.5.1
pycrypto==2.6.1
PyGObject==3.30.4
python-daemon==2.2.4
pyxdg==0.25
PyYAML==5.1.2
requests==2.22.0
RPi.GPIO==0.7.0
SecretStorage==2.3.1
six==1.12.0
subprocess32==3.5.4
twentyc.tmpl==0.2.0
urllib3==1.25.6
vaping==1.1.0
vodka==2.2.6
Werkzeug==0.16.0
whichcraft==0.6.1

**Comment by vegu** [comment] 2019-10-31 17:05
@jiberan @baristan93  Pushed a patch that fixed what i was able to reproduce running `python3.6`. I have not been able to reproduce the issue on `python2.7.15`, but since it's a race condition maybe we'll be lucky and it fixes your end as well.

Can you please try the following and let me know if that fixes your issue 

```
pip uninstall vaping -y
pip install https://github.com/20c/vaping/archive/master.zip
```

If it doesn't fix it, you could also try downgrading your `python-daemon` install since 2.2.4 no longer officially supports python2.7 (although i did run it with that install and it worked ok for me, so perhaps a long shot)

**Comment by jiberan** [comment] 2019-10-31 19:37
I can also confirm, that patch is not working for `python 2.7.16`.  I did try to install `python3.6`, but for now, I don't know how to run in under this version.

**Comment by vegu** [comment] 2019-10-31 20:00
Are both of you running on Raspbian?

**Comment by baristan93** [comment] 2019-10-31 20:07
yes, buster.

**Comment by vegu** [comment] 2019-10-31 20:23
I have a rpi lying around somewhere, will try to reproduce there when i have some time

**Comment by jiberan** [comment] 2019-11-01 10:01
yes. I'm running Raspbian.

**Comment by vegu** [comment] 2019-11-05 14:51
managed to reproduce on my rpi (running centos) and on a virtualbox running raspbian, not sure on the cause yet or if they are failing because of the same reason, but it's a step towards a fix :)

**Comment by vegu** [comment] 2019-11-05 16:30
@jiberan @baristan93 pushed a fix to the `daemon_gevent_fixes` branch, please see if that fixes your issues as well

to install:

```
pip uninstall vaping -y
pip install https://github.com/20c/vaping/archive/daemon_gevent_fixes.zip
```

**Comment by jiberan** [comment] 2019-11-06 16:57
I can confirm, that it is working. Thanks!

**Comment by vegu** [comment] 2019-11-11 09:54
@jiberan thanks for the confirmation, fix will be rolled into next release (tracked in #73 now)

**Closed by vegu** 2019-11-11 09:54 UTC
