### ISSUE TITLE
Crash after running for several days

### ISSUE THREAD

**Issue by mattlan** [20c/vaping#134] opened 2021-09-21 14:33 UTC
vaping version: 1.4.2
pypy version: 7.3.5 (python 3.7.10)
fping version: 3.10

vaping config:
```
probes:
  - name: latency
    type: std_fping
    output:
      - prometheus
    testing_hosts:
      hosts:
        - host: 1.1.1.1
          name: Cloudflare DNS
        # few internal hosts omitted
plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s
    output:
      - prometheus
  - name: prometheus
    type: prometheus
    port: 9090
```

After running fine for several days, crashes and outputs the following exception:
```
vaping.daemon 'NoneType' object has no attribute 'get' daemon.py:214
PidFile <pid.posix.PidFile object at 0x00007fe8501e2560> closing pidfile: /root/vaping.pid base.py:220
vaping.daemon stopping prometheus daemon.py:254
vaping.daemon stopping latency daemon.py:254
PidFile <pid.posix.PidFile object at 0x00007fe8501e2560> closing pidfile: /root/vaping.pid base.py:220
```

Has currently happened twice now, but since I normally redirect all the debug output (due to #88) I was not able to get the exception output for the prior crash.  Restarted it again and will continue logging the debug output for now.

**Comment by vegu** [comment] 2021-09-22 08:45
Thanks for the report - curious to see what the debug output looks like

Also seems like daemon.py:214 should log the traceback instead of just the error message.

What os are you running vaping  on ?

**Comment by mattlan** [comment] 2021-09-22 19:34
This is CentOS 7.  That is the debug output, as it will crash without as per the mentioned issue.  Is there a way to get more verbose debug output that I'm missing?  If there is happy to enable it and continue monitoring.

**Comment by vegu** [comment] 2021-09-23 09:58
If you are ok with doing code changes to the vaping source you could change daemon.py:214 from

```
self.log.error(exc)
```

to

```
import traceback
self.log.error(traceback.format_exc())
```

**Comment by mattlan** [comment] 2021-09-23 18:13
Indeed, I can do that.  Though the issue will take several days to manifest so it may be a bit before I have anything to report back.

**Comment by mattlan** [comment] 2021-09-24 13:38
Looks like it manifested quicker this time.  Traceback seems to indicate it's coming from the prometheus plugin.
```
vaping.daemon Traceback (most recent call last):
  File "/srv/vaping/site-packages/vaping/daemon.py", line 212, in _main
    vaping.io.join_plugins(self.joins)
  File "/srv/vaping/site-packages/vaping/io.py", line 32, in join_plugins
    asyncio_run(run_plugins())
  File "/srv/vaping/lib-python/3/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/srv/vaping/lib-python/3/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/srv/vaping/lib-python/3/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/srv/vaping/lib-python/3/asyncio/tasks.py", line 251, in __step
    result = coro.throw(exc)
  File "/srv/vaping/site-packages/vaping/io.py", line 30, in run_plugins
    await asyncio.gather(*tasks)
  File "/srv/vaping/lib-python/3/asyncio/futures.py", line 263, in __await__
    yield self  # This tells Task to wait for completion.
  File "/srv/vaping/lib-python/3/asyncio/tasks.py", line 318, in __wakeup
    future.result()
  File "/srv/vaping/lib-python/3/asyncio/futures.py", line 181, in result
    raise self._exception
  File "/srv/vaping/lib-python/3/asyncio/tasks.py", line 249, in __step
    result = coro.send(None)
  File "/srv/vaping/site-packages/vaping/plugins/__init__.py", line 282, in _run
    await self.emit_all()
  File "/srv/vaping/site-packages/vaping/plugins/__init__.py", line 252, in emit_all
    await self.send_emission()
  File "/srv/vaping/site-packages/vaping/plugins/__init__.py", line 245, in send_emission
    await emit()
  File "/srv/vaping/site-packages/vaping/plugins/__init__.py", line 229, in emit
    emitter.emit(msg)
  File "/srv/vaping/config/plugins/prometheus.py", line 24, in emit
    host_name = host_data.get('host')
AttributeError: 'NoneType' object has no attribute 'get'
 daemon.py:217
PidFile <pid.posix.PidFile object at 0x00007ff7c99fe448> closing pidfile: /root/vaping.pid base.py:220
vaping.daemon stopping prometheus daemon.py:257
vaping.daemon stopping latency daemon.py:257
PidFile <pid.posix.PidFile object at 0x00007ff7c99fe448> closing pidfile: /root/vaping.pid base.py:220
```

**Comment by vegu** [comment] 2021-10-05 06:31
@mattlan we just merged a fix that may address this issue via #137

**Comment by mattlan** [comment] 2021-10-05 21:25
Thanks!  Also thanks to @simonlindberg!  I've added the fix to my own `plugins/__init__.py`.  Will report back if I encounter additional issues with this specific problem.

**Comment by simonlindberg** [comment] 2021-10-12 19:48
@mattlan I think you are seeing the same issue as me, but the implementation of `prometheus` and `graphite` differ.
I use the builtin plugin for  [graphite](https://github.com/20c/vaping/blob/master/src/vaping/plugins/graphite.py), which is implementing [update](https://github.com/20c/vaping/blob/826956a4b96f52d6d1b53a73047ac28d7690591a/src/vaping/plugins/__init__.py#L501-L511) as intended. 

Which `prometheus.py` implementation are you using? Assuming that you are using this [prometheus.py](https://github.com/bojanrajkovic/vaping-exporter/blob/master/prometheus.py#L20), it is re-implementing [emit](https://github.com/20c/vaping/blob/826956a4b96f52d6d1b53a73047ac28d7690591a/src/vaping/plugins/__init__.py#L567-L600) which is where I put my patch, thereby ignoring it.

**Comment by mattlan** [comment] 2021-10-13 00:57
Very likely, and yes, the one you linked is the one I am using.  Your PR fixes the issue if the row is None, however, my issue is caused by this data which will not meet that condition:
```
vaping.plugins.prometheus data: [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, {'host': 'host1.example', 'cnt': 10, 'loss': 0.0, 'data': [0.26, 0.23, 0.3, 0.25, 0.3, 0.26, 0.3, 0.26, 0.27, 0.23], 'min': 0.23, 'max': 0.3, 'avg': 0.266, 'last': 0.23}, {'host': '1.1.1.1', 'cnt': 10, 'loss': 0.0, 'data': [1.29, 1.45, 1.34, 1.31, 1.33, 1.38, 1.4, 1.41, 1.44, 1.36], 'min': 1.29, 'max': 1.45, 'avg': 1.371, 'last': 1.36}, {'host': 'host2.example', 'cnt': 10, 'loss': 0.4, 'data': [45.92, 45.99, 45.91, 45.92, 45.92, 45.9], 'min': 45.9, 'max': 45.99, 'avg': 45.92666666666667, 'last': 45.9}, {'host': 'host3.example', 'cnt': 10, 'loss': 0.4, 'data': [46.5, 46.48, 46.42, 46.51, 46.49], 'min': 46.33, 'max': 46.51, 'avg': 46.429, 'last': 46.49}] prometheus.py:22
```

Example:
```
>>> data = [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, {'host': 'host1.example', 'cnt': 10, 'loss': 0.0, 'data': [0.26, 0.23, 0.3, 0.25, 0.3, 0.26, 0.3, 0.26, 0.27, 0.23], 'min': 0.23, 'max': 0.3, 'avg': 0.266, 'last': 0.23}, {'host': '1.1.1.1', 'cnt': 10, 'loss': 0.0, 'data': [1.29, 1.45, 1.34, 1.31, 1.33, 1.38, 1.4, 1.41, 1.44, 1.36], 'min': 1.29, 'max': 1.45, 'avg': 1.371, 'last': 1.36}, {'host': 'host2.example', 'cnt': 10, 'loss': 0.4, 'data': [45.92, 45.99, 45.91, 45.92, 45.92, 45.9], 'min': 45.9, 'max': 45.99, 'avg': 45.92666666666667, 'last': 45.9}, {'host': 'host3.example', 'cnt': 10, 'loss': 0.4, 'data': [46.5, 46.48, 46.42, 46.51, 46.49], 'min': 46.33, 'max': 46.51, 'avg': 46.429, 'last': 46.49}]
>>> data is None
False
>>> None in data
True
```

**Comment by mattlan** [comment] 2021-10-20 20:35
Just as an update... so far so good after patching the prometheus plugin.

**Closed** 2022-03-15 11:30 UTC
Labels: bug
